services:
  pacifico:
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`localhost`)
      - traefik.http.routers.api.tls=false
      - traefik.http.routers.api.tls.certresolver=
      - traefik.http.services.api.loadbalancer.server.port=80

  traefik:
    image: traefik:v2.3
    ports:
      - 80:80
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - traefik-public-certificates:/certificates

  vector:
    profiles:
      - "norun"
volumes:
  traefik-public-certificates:
