FROM python:3.9-slim

WORKDIR /app

COPY ./pacifico/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./logconfig ./
COPY ./pacifico/*.py ./

CMD ["python",  "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
