# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY ./corona/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy your Python script and start.sh
COPY ./logconfig ./
COPY ./corona/*.py ./

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Set the entrypoint to your start.sh script
ENTRYPOINT ["python", "main.py"]
