FROM golang:alpine AS build
WORKDIR /app
COPY ./modelo/go.mod ./modelo/go.sum ./
RUN go mod download
COPY ./modelo/*.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o modelo

FROM alpine:3.18
ENV TZ=UTC
# Install only what's needed for cron
RUN apk add --no-cache dcron ca-certificates tzdata
WORKDIR /app
COPY --from=build /app/modelo ./
COPY ./modelo/start.sh ./
RUN chmod +x ./start.sh && touch /var/log/cron.log
ENTRYPOINT ["./start.sh"]
