services:
  pacifico:
    image: manifoldlabs/targon-pacifico
    labels:
      - traefik.enable=true
      - traefik.http.routers.pacifico.rule=Host(`jugo.targon.com`) || Host(`beers.targon.com`)
      - traefik.http.routers.pacifico.tls=true
      - traefik.http.routers.pacifico.tls.certresolver=letsencrypt
      - traefik.http.services.pacifico.loadbalancer.server.port=80
      - vector.enable=true
    build:
      context: .
      dockerfile: Dockerfile.pacifico
    networks:
      - targon-beers
    env_file: .env
    depends_on:
      mongodb:
        condition: service_healthy

  modelo:
    image: manifoldlabs/targon-modelo
    labels:
      - vector.enable=true
    build:
      context: .
      dockerfile: Dockerfile.modelo
    env_file: .env
    volumes:
      - ./data/archives:/data/archives
  corona:
    image: manifoldlabs/targon-corona
    labels:
      - vector.enable=true
    build:
      context: .
      dockerfile: Dockerfile.corona
    env_file: .env

  traefik:
    image: traefik:v2.3
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - traefik-public-certificates:/certificates
    networks:
      - targon-beers
  
  vector:
    image: timberio/vector:0.43.0-debian
    environment:
      - INFLUX_ENDPOINT=${INFLUX_ENDPOINT}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    volumes:
      - ./vector.toml:/etc/vector/vector.toml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --config /etc/vector/vector.toml
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - targon-beers
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-targon}
      - MONGO_HOST=${MONGO_HOST:-jugo.targon.com}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

networks:
  targon-beers:

volumes:
  traefik-public-certificates:
  mongodb_data: