services:
  pacifico:
    platform: linux/arm64
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    labels:
      - traefik.enable=true
      - traefik.http.routers.pacifico.rule=Host(`localhost`)
      - traefik.http.routers.pacifico.tls=false
      - traefik.http.routers.pacifico.tls.certresolver=
      - traefik.http.services.pacifico.loadbalancer.server.port=80
      - vector.enable=false
    networks:
      - targon-beers

  modelo:
    platform: linux/arm64
    labels:
      - vector.enable=false
  corona:
    platform: linux/arm64
    labels:
      - vector.enable=false

  traefik:
    image: traefik:v2.3
    ports:
      - 80:80
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.dev.toml:/etc/traefik/traefik.toml
      - traefik-public-certificates:/certificates
    networks:
      - targon-beers
  
  vector:
    profiles:
      - "norun"

  mongodb:
    platform: linux/arm64
    ports:
      - "27017:27017"  # Simplified port binding
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=targon
    volumes:
      - mongodb_data:/data/db
    networks:
      - targon-beers
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  targon-beers:

volumes:
  traefik-public-certificates:
  mongodb_data:
